#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://pivot-astakhov.uaa.run.pcfone.io/oauth/token
management:
  endpoints:
    web:
      exposure:
        include: "*"